name: Run AI Video Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Jupyter
        run: |
          pip install notebook nbconvert

      - name: Run notebook and upload
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ELEVEN_API_KEY: ${{ secrets.ELEVEN_API_KEY }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "$CLIENT_SECRET" > client_secret.json
          jupyter nbconvert --to python --output run_video_generator ai_video_generator_with_youtube.ipynb
          python3 run_video_generator.py
